data_name: random
buffer_size: 12
container_dx: 600
container_dy: 600
container_dz: 600
k_placement: 80
remove_inscribed_ems: false
train_env_num: 64
test_env_num: 32
train_env_seed: 5
max_epoch: 1000
step_per_epoch: 32000
step_per_collect: 4000
episode_per_test: 128
batch_size: 256
learning_rate: 0.00007
output_root: train_outputs
output_name:
tb_log_dir:
resume_checkpoint:
