data_name: CJ
buffer_size: 12
container_dx: 1200
container_dy: 1000
container_dz: 1350
k_placement: 80
remove_inscribed_ems: false
stack_only: true
use_simple_blocks: true
policy_mode: largest_block_baseline
layered_achievability: false
layered_num_chunks: 3
train_env_num: 64
test_env_num: 32
train_env_seed: 5
max_epoch: 1000
step_per_epoch: 32000
step_per_collect: 1000
episode_per_test: 128
batch_size: 256
learning_rate: 0.00007
output_root: outputs/train_outputs
output_name: baseline-blocks
tb_log_dir:
resume_checkpoint:
